name: Event data shell flow 4
on: pull_request_review
permissions:
  contents: read
jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: Print event data
        run: "printf '%s\\n' ${{ github.event.review.body }}"
