import { build } from "esbuild";
import { rm } from "node:fs/promises";

await Promise.all([
  rm("dist/action/index.js", { force: true }),
  rm("dist/action/index.js.map", { force: true }),
]);
await build({
  entryPoints: ["src/action.ts"],
  outfile: "dist/action/index.cjs",
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node20",
  sourcemap: true,
  sourcesContent: false,
  banner: {
    js: "/* Bundled action entrypoint. Generated by npm run build:action. */",
  },
});
